from __future__ import annotations

import argparse
from importlib import metadata
import os
from pathlib import Path
import sys

from .config import resolve_elastic_settings
from .diagnostics import (
    enrich_result,
    render_result_json,
    render_result_junit,
)
from .engine import TraceEngine
from .report import render_json, render_text
from .spec import SpecError, load_spec


STARTER = """spec_version: detectspec/v1
id: DET-EXAMPLE-001
title: Example detection

behavior:
  mitre:
    technique: T1059.001

inputs:
  profiles:
    local:
      execution: execution.json
      source: source.jsonl
      collector: collector.jsonl
      normalized: normalized.jsonl
      alerts: alerts.jsonl

checkpoints:
  execution:
    require:
      - field: executed
        op: equals
        value: true

  source:
    require_event:
      all:
        - field: event.code
          op: equals
          value: 1

  collector:
    require_event:
      all:
        - field: event.code
          op: equals
          value: 1

  normalization:
    required_fields:
      - process.name
      - process.command_line

  rule:
    match:
      all:
        - field: process.name
          op: endswith
          value: powershell.exe

  alert:
    require_event:
      all:
        - field: alert.rule_id
          op: equals
          value: DET-EXAMPLE-001
"""

STARTER_README = """# DetectTrace starter project

This project was generated by `detecttrace init`.

## Validate the DetectSpec

```powershell
detecttrace validate detectspec.yaml
```

## Run the local detection trace

```powershell
detecttrace test detectspec.yaml
```

The generated `local` profile is self-contained and uses the evidence files in
this directory. It does not require Elasticsearch, Kibana, Docker, or network
access.

When you are ready to test a live Elastic detection pipeline, configure
DetectTrace separately and run `detecttrace doctor` first.
"""


def _installed_version() -> str:
    try:
        return metadata.version("detecttrace")
    except metadata.PackageNotFoundError:
        return "unknown"


def _select_profile(
    spec: dict[str, object],
    requested: str | None,
) -> str:
    profiles = spec["inputs"]["profiles"]

    if requested is not None:
        return requested

    for preferred in ("local", "healthy"):
        if preferred in profiles:
            return preferred

    return next(iter(profiles))


def cmd_validate(args: argparse.Namespace) -> int:
    path = Path(args.spec)
    load_spec(path)
    print(f"VALID  {path}")
    return 0


def cmd_test(args: argparse.Namespace) -> int:
    path = Path(args.spec)
    spec = load_spec(path)
    profile = _select_profile(spec, args.profile)

    engine = TraceEngine()
    result = engine.run(spec, path, profile)

    if args.format == "json":
        print(render_json(result))
    else:
        print(render_text(result, verbose=args.verbose))

    return 0 if result.healthy else 1


def cmd_init(args: argparse.Namespace) -> int:
    directory = Path(args.directory)
    directory.mkdir(parents=True, exist_ok=True)

    files = {
        "detectspec.yaml": STARTER,
        "execution.json": '{"executed": true}\n',
        "source.jsonl": (
            '{"event":{"code":1},"process":{"name":"powershell.exe",'
            '"command_line":"powershell.exe -enc AAA"}}\n'
        ),
        "collector.jsonl": (
            '{"event":{"code":1},"process":{"name":"powershell.exe",'
            '"command_line":"powershell.exe -enc AAA"}}\n'
        ),
        "normalized.jsonl": (
            '{"event":{"code":1},"process":{"name":"powershell.exe",'
            '"command_line":"powershell.exe -enc AAA"}}\n'
        ),
        "alerts.jsonl": (
            '{"alert":{"rule_id":"DET-EXAMPLE-001"}}\n'
        ),
        "README.md": STARTER_README,
    }

    conflicts = [
        name
        for name in files
        if (directory / name).exists()
    ]

    if conflicts and not args.force:
        raise ValueError(
            f"{directory} already contains DetectTrace starter file(s): "
            + ", ".join(conflicts)
            + ". Use --force to overwrite."
        )

    for name, contents in files.items():
        (directory / name).write_text(
            contents,
            encoding="utf-8",
        )

    # The generator must never emit a DetectSpec that DetectTrace itself
    # considers invalid.
    load_spec(directory / "detectspec.yaml")

    print(f"Created DetectTrace starter project in {directory}")
    print()
    print("Next:")
    print(f"  cd {directory}")
    print("  detecttrace validate detectspec.yaml")
    print("  detecttrace test detectspec.yaml")
    return 0


def cmd_sentinel_status(args: argparse.Namespace) -> int:
    try:
        from .adapters.sentinel import SentinelAdapter
    except ImportError as exc:
        print(
            "ERROR: Sentinel support requires Azure dependencies. "
            "Run: pip install -e .",
            file=sys.stderr,
        )
        print(f"DETAIL: {exc}", file=sys.stderr)
        return 2

    adapter = SentinelAdapter(workspace_id=args.workspace_id)
    checks = adapter.status()

    print()
    print("DETECTTRACE — SENTINEL STATUS")
    print("=" * 72)

    labels = {
        "authentication": "Azure authentication",
        "workspace": "Workspace configured",
        "query": "Log Analytics query",
    }

    healthy = True

    for key, (passed, message) in checks.items():
        state = "PASS" if passed else "FAIL"
        print(f"{labels.get(key, key):<26} {state:<8} {message}")
        healthy = healthy and passed

    print()
    return 0 if healthy else 1


def cmd_elastic_status(args: argparse.Namespace) -> int:
    try:
        from .adapters.elastic import ElasticAdapter
    except ImportError as exc:
        print("ERROR: Elastic adapter could not be loaded.", file=sys.stderr)
        print(f"DETAIL: {exc}", file=sys.stderr)
        return 2

    adapter = ElasticAdapter(base_url=args.url)
    checks = adapter.status(index=args.index)

    print()
    print("DETECTTRACE — ELASTIC STATUS")
    print("=" * 72)

    labels = {
        "connection": "Elasticsearch connection",
        "index": "Telemetry index",
    }

    healthy = True

    for key, (passed, message) in checks.items():
        state = "PASS" if passed else "FAIL"
        print(f"{labels.get(key, key):<26} {state:<8} {message}")
        healthy = healthy and passed

    print()
    return 0 if healthy else 1



def cmd_elastic_trace(args: argparse.Namespace) -> int:
    try:
        from .adapters.elastic import ElasticAdapter
    except ImportError as exc:
        print("ERROR: Elastic adapter could not be loaded.", file=sys.stderr)
        print(f"DETAIL: {exc}", file=sys.stderr)
        return 2

    spec_path = Path(args.spec)
    spec = load_spec(spec_path)
    adapter = ElasticAdapter(base_url=args.url)
    result = adapter.trace_spec(
        spec=spec,
        index=args.index,
        limit=args.limit,
    )

    print()
    print("DETECTTRACE — ELASTIC LIVE TRACE")
    print("=" * 72)
    print(f"{spec['id']} — {spec['title']}")
    print()

    for stage in result["stages"]:
        print(
            f"{stage['name']:<26} "
            f"{stage['status']:<8} "
            f"{stage['summary']}"
        )

    print()
    print("ROOT CAUSE")
    print("-" * 72)
    print(result["root_cause"])
    print(f"Confidence: {result['confidence']}")
    print()

    return 0 if result["healthy"] else 1


def cmd_elastic_alert(args: argparse.Namespace) -> int:
    try:
        from .adapters.elastic import ElasticAdapter
    except ImportError as exc:
        print("ERROR: Elastic adapter could not be loaded.", file=sys.stderr)
        print(f"DETAIL: {exc}", file=sys.stderr)
        return 2

    import getpass

    password = os.getenv("DETECTTRACE_ELASTIC_PASSWORD")
    if not password:
        password = getpass.getpass("Elastic password: ")

    adapter = ElasticAdapter(base_url=args.url)
    result = adapter.verify_alert(
        rule_name=args.rule_name,
        kibana_url=args.kibana_url,
        username=args.username,
        password=password,
    )

    print()
    print("DETECTTRACE — ELASTIC ALERT VERIFICATION")
    print("=" * 72)
    print(f"Kibana alert query         {result['status']:<8} {result['summary']}")

    alert = result.get("alert")
    if alert:
        print(f"Rule                       PASS     {alert['rule_name']}")
        print(f"Alert timestamp            PASS     {alert['timestamp']}")
        print(f"Alert status               PASS     {alert['status']}")
        print(f"Severity                   PASS     {alert['severity']}")
        if alert.get("risk_score") is not None:
            print(f"Risk score                 PASS     {alert['risk_score']}")
        print()
        print("ALERT CONFIRMED")
        print("-" * 72)
        print("Elastic Security generated a real alert for the requested rule.")
    else:
        print()
        print("ALERT NOT CONFIRMED")
        print("-" * 72)
        print(result["summary"])

    print()
    return 0 if result["healthy"] else 1


def cmd_elastic_test(args: argparse.Namespace) -> int:
    try:
        from .adapters.elastic import ElasticAdapter
    except ImportError as exc:
        print("ERROR: Elastic adapter could not be loaded.", file=sys.stderr)
        print(f"DETAIL: {exc}", file=sys.stderr)
        return 2

    import getpass

    spec_path = Path(args.spec)
    spec = load_spec(spec_path)
    settings = resolve_elastic_settings(args)

    password = os.getenv("DETECTTRACE_ELASTIC_PASSWORD")
    if not password:
        password = getpass.getpass("Elastic password: ")

    adapter = ElasticAdapter(
        base_url=settings["url"],
        username=settings["username"],
        password=password,
        verify_tls=not settings["insecure"],
        ca_cert=settings["ca_cert"],
    )

    connected, connection_summary = adapter.check_connection()
    if not connected:
        print(
            f"ERROR: Elasticsearch preflight failed: "
            f"{connection_summary}",
            file=sys.stderr,
        )

        lowered = connection_summary.lower()
        if (
            "certificate_verify_failed" in lowered
            or "certificate verify failed" in lowered
            or "self-signed certificate" in lowered
        ):
            print(
                "HINT: Configure elastic.ca_cert in .detecttrace.yaml "
                "or pass --ca-cert with Elasticsearch's HTTP CA "
                "certificate. Use --insecure only for temporary "
                "troubleshooting.",
                file=sys.stderr,
            )

        return 2

    result = adapter.correlated_test(
        spec=spec,
        index=settings["index"],
        rule_name=args.rule_name,
        kibana_url=settings["kibana_url"],
        case=args.case,
        kibana_username=settings["username"],
        kibana_password=password,
        limit=args.limit,
        alert_timeout=args.timeout,
        poll_interval=args.poll_interval,
    )

    enrich_result(
        result,
        spec_id=spec["id"],
        spec_title=spec["title"],
        backend="elastic",
        rule_name=args.rule_name,
    )

    if args.format == "json":
        print(render_result_json(result))
        return 0 if result["healthy"] else 1

    if args.format == "junit":
        print(render_result_junit(result))
        return 0 if result["healthy"] else 1

    print()
    print("DETECTTRACE — CORRELATED END-TO-END TEST")
    print("=" * 72)
    print(f"{spec['id']} — {spec['title']}")
    if result.get("run_id"):
        print(f"Run ID: {result['run_id']}")
    print(f"Case: {result.get('case', args.case)}")
    if settings.get("config_path"):
        print(f"Config: {settings['config_path']}")
    print()

    for stage in result["stages"]:
        print(
            f"{stage['name']:<26} "
            f"{stage['status']:<8} "
            f"{stage['summary']}"
        )

    print()
    print("RESULT")
    print("-" * 72)
    print(result["root_cause"])
    print(f"Confidence: {result['confidence']}")

    if not result["healthy"]:
        print(
            "First failing stage: "
            f"{result.get('first_failed_stage') or 'UNKNOWN'}"
        )
        print(
            "Failure code: "
            f"{result.get('failure_code') or 'UNKNOWN'}"
        )
        if result.get("remediation"):
            print(f"Recommended remediation: {result['remediation']}")

    if result.get("indexing_ms") is not None:
        print(f"Indexing round-trip: {result['indexing_ms']:.1f} ms")
    if result.get("alert_latency_s") is not None:
        print(f"Approx. alert latency: {result['alert_latency_s']:.2f} s")

    alert = result.get("alert")
    if alert:
        print()
        print(f"Alert status: {alert.get('status', 'unknown')}")
        print(f"Severity: {alert.get('severity', 'unknown')}")
        if alert.get("risk_score") is not None:
            print(f"Risk score: {alert['risk_score']}")

    print()
    return 0 if result["healthy"] else 1



def cmd_doctor(args: argparse.Namespace) -> int:
    import getpass

    try:
        settings = resolve_elastic_settings(args)
    except ValueError as exc:
        print()
        print("DETECTTRACE — DOCTOR")
        print("=" * 72)
        print(
            f"{'Configuration':<26} "
            f"{'FAIL':<8} "
            f"{exc}"
        )
        print()
        print("RESULT")
        print("-" * 72)
        print("Environment is not ready for DetectTrace.")
        print()
        return 2

    password = os.getenv("DETECTTRACE_ELASTIC_PASSWORD")
    if not password:
        password = getpass.getpass("Elastic password: ")

    from .doctor import run_doctor

    result = run_doctor(
        settings=settings,
        password=password,
    )

    print()
    print("DETECTTRACE — DOCTOR")
    print("=" * 72)

    for check in result["checks"]:
        print(
            f"{check['name']:<26} "
            f"{check['status']:<8} "
            f"{check['summary']}"
        )

    print()
    print("RESULT")
    print("-" * 72)

    if result["healthy"]:
        print(
            "Environment is ready for DetectTrace Elastic "
            "detection testing."
        )
        exit_code = 0
    else:
        print(
            "Environment is not ready for DetectTrace. "
            "Resolve the failed environment checks before "
            "running a detection test."
        )
        exit_code = 2

    print()
    return exit_code

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="detecttrace",
        description="Executable contracts and causal tracing for security detections.",
    )
    parser.add_argument(
        "--version",
        action="version",
        version=f"%(prog)s {_installed_version()}",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("validate", help="validate a DetectSpec")
    p.add_argument("spec")
    p.set_defaults(func=cmd_validate)

    p = sub.add_parser("test", help="execute a DetectSpec trace")
    p.add_argument(
        "spec",
        help="path to a DetectSpec YAML file",
    )
    p.add_argument(
        "--profile",
        default=None,
        help=(
            "input profile to run "
            "(default: local, then healthy, then first available)"
        ),
    )
    p.add_argument("--format", choices=("text", "json"), default="text")
    p.add_argument("-v", "--verbose", action="store_true")
    p.set_defaults(func=cmd_test)

    p = sub.add_parser(
        "init",
        help="create a runnable starter DetectSpec project",
    )
    p.add_argument(
        "directory",
        help="directory to create or populate",
    )
    p.add_argument(
        "--force",
        action="store_true",
        help="overwrite existing DetectTrace starter files",
    )
    p.set_defaults(func=cmd_init)

    p = sub.add_parser(
        "doctor",
        help="check whether the local Elastic environment is ready",
    )
    p.add_argument(
        "--config",
        default=None,
        help=(
            "DetectTrace YAML config path "
            "(default: DETECTTRACE_CONFIG, .detecttrace.yaml, "
            "or ~/.detecttrace/config.yaml)"
        ),
    )
    p.add_argument(
        "--url",
        default=None,
        help="Elasticsearch URL (CLI > environment > config > default)",
    )
    p.add_argument(
        "--kibana-url",
        default=None,
        help="Kibana URL (CLI > environment > config > default)",
    )
    p.add_argument(
        "--username",
        default=None,
        help="Elastic username (CLI > environment > config > default)",
    )
    p.add_argument(
        "--index",
        default=None,
        help="Telemetry index (CLI > environment > config > default)",
    )
    p.add_argument(
        "--ca-cert",
        default=None,
        help="Path to Elasticsearch HTTP CA certificate",
    )
    p.set_defaults(func=cmd_doctor)

    p = sub.add_parser(
        "sentinel",
        help="Microsoft Sentinel / Log Analytics operations",
    )
    sentinel_sub = p.add_subparsers(
        dest="sentinel_command",
        required=True,
    )
    status = sentinel_sub.add_parser(
        "status",
        help="check Sentinel connectivity",
    )
    status.add_argument(
        "--workspace-id",
        help=(
            "Log Analytics workspace ID "
            "(or set DETECTTRACE_SENTINEL_WORKSPACE_ID)"
        ),
    )
    status.set_defaults(func=cmd_sentinel_status)

    p = sub.add_parser(
        "elastic",
        help="Elasticsearch operations",
    )
    elastic_sub = p.add_subparsers(
        dest="elastic_command",
        required=True,
    )
    elastic_status = elastic_sub.add_parser(
        "status",
        help="check Elasticsearch connectivity and telemetry index",
    )
    elastic_status.add_argument(
        "--url",
        default=None,
        help=(
            "Elasticsearch base URL "
            "(default: DETECTTRACE_ELASTIC_URL or http://localhost:9200)"
        ),
    )
    elastic_status.add_argument(
        "--index",
        default="detecttrace-events",
        help="Telemetry index to check (default: detecttrace-events)",
    )
    elastic_status.set_defaults(func=cmd_elastic_status)

    elastic_trace = elastic_sub.add_parser(
        "trace",
        help="evaluate a DetectSpec against live Elasticsearch telemetry",
    )
    elastic_trace.add_argument(
        "spec",
        help="Path to a DetectSpec YAML file",
    )
    elastic_trace.add_argument(
        "--url",
        default=None,
        help=(
            "Elasticsearch base URL "
            "(default: DETECTTRACE_ELASTIC_URL or http://localhost:9200)"
        ),
    )
    elastic_trace.add_argument(
        "--index",
        default="detecttrace-events",
        help="Telemetry index to evaluate (default: detecttrace-events)",
    )
    elastic_trace.add_argument(
        "--limit",
        type=int,
        default=10,
        help="Number of recent documents to evaluate (default: 10)",
    )
    elastic_trace.set_defaults(func=cmd_elastic_trace)

    elastic_alert = elastic_sub.add_parser(
        "alert",
        help="verify that Elastic Security generated a real alert",
    )
    elastic_alert.add_argument(
        "--rule-name",
        required=True,
        help="Elastic Security detection rule name",
    )
    elastic_alert.add_argument(
        "--kibana-url",
        default=os.getenv("DETECTTRACE_KIBANA_URL", "http://localhost:5602"),
        help="Kibana URL",
    )
    elastic_alert.add_argument(
        "--username",
        default=os.getenv("DETECTTRACE_ELASTIC_USERNAME", "elastic"),
        help="Elastic username",
    )
    elastic_alert.add_argument(
        "--url",
        default=None,
        help="Elasticsearch base URL",
    )
    elastic_alert.set_defaults(func=cmd_elastic_alert)

    elastic_test = elastic_sub.add_parser(
        "test",
        help="run an end-to-end DetectSpec test against secured Elastic",
    )
    elastic_test.add_argument(
        "spec",
        help="Path to a DetectSpec YAML file",
    )
    elastic_test.add_argument(
        "--rule-name",
        required=True,
        help="Elastic Security detection rule name",
    )
    elastic_test.add_argument(
        "--config",
        default=None,
        help=(
            "DetectTrace YAML config path "
            "(default: DETECTTRACE_CONFIG, .detecttrace.yaml, "
            "or ~/.detecttrace/config.yaml)"
        ),
    )
    elastic_test.add_argument(
        "--url",
        default=None,
        help=(
            "Elasticsearch URL "
            "(CLI > environment > config > secure default)"
        ),
    )
    elastic_test.add_argument(
        "--kibana-url",
        default=None,
        help=(
            "Kibana URL "
            "(CLI > environment > config > default)"
        ),
    )
    elastic_test.add_argument(
        "--username",
        default=None,
        help=(
            "Elastic username "
            "(CLI > environment > config > default)"
        ),
    )
    elastic_test.add_argument(
        "--index",
        default=None,
        help=(
            "Telemetry index "
            "(CLI > environment > config > default)"
        ),
    )
    elastic_test.add_argument(
        "--limit",
        type=int,
        default=10,
        help="Number of recent telemetry documents to inspect (default: 10)",
    )
    elastic_test.add_argument(
        "--case",
        default="healthy",
        help="DetectSpec test case to run (default: healthy)",
    )
    elastic_test.add_argument(
        "--timeout",
        type=float,
        default=90.0,
        help="Seconds to wait for a correlated Elastic alert (default: 90)",
    )
    elastic_test.add_argument(
        "--poll-interval",
        type=float,
        default=5.0,
        help="Alert polling interval in seconds (default: 5)",
    )
    elastic_test.add_argument(
        "--format",
        choices=("text", "json", "junit"),
        default="text",
        help="Output format (default: text)",
    )
    elastic_test.add_argument(
        "--ca-cert",
        default=None,
        help="Path to Elasticsearch HTTP CA certificate",
    )
    elastic_test.add_argument(
        "--insecure",
        action="store_true",
        help="Disable TLS certificate verification (local lab only)",
    )
    elastic_test.set_defaults(func=cmd_elastic_test)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        return args.func(args)
    except (SpecError, ValueError, FileNotFoundError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
